#!/bin/bash

echo "🧪 Stripe Local Webhook Test Guide"
echo "================================="
echo ""
echo "1. First, make sure Stripe CLI is installed:"
echo "   brew install stripe/stripe-cli/stripe"
echo ""
echo "2. In Terminal 1, start your dev server:"
echo "   npm run dev"
echo ""
echo "3. In Terminal 2, start webhook forwarding:"
echo "   stripe listen --forward-to localhost:3000/api/webhooks/stripe"
echo ""
echo "4. Copy the webhook secret shown (whsec_test_xxx) and add to .env.local:"
echo "   STRIPE_WEBHOOK_SECRET=whsec_test_xxx"
echo ""
echo "5. Restart your dev server to load new env var"
echo ""
echo "6. In Terminal 3, trigger a test event:"
echo "   stripe trigger checkout.session.completed"
echo ""
echo "Or make a real test purchase and watch Terminal 2 for events!"
echo ""
echo "📊 Check results with:"
echo "SELECT * FROM \"bazaar-vid_credit_transaction\" WHERE type = 'purchase' ORDER BY created_at DESC LIMIT 5;"