#!/bin/bash
# scripts/setup-env.sh - Generate .env.local with all required variables from Codex

# Create log directories
mkdir -p /tmp/bazaar-logs /tmp/a2a-logs /tmp/error-logs /tmp/combined-logs

# Set output file
ENV_FILE=".env.local"

echo "🔧 Setting up $ENV_FILE with real environment variables..."

# Check if file exists and overwrite without prompting
if [ -f "$ENV_FILE" ]; then
  echo "⚠️  Overwriting existing $ENV_FILE"
fi

# Create .env.local with environment variables
cat > "$ENV_FILE" << EOL
# ${ENV_FILE} - Generated by setup-env.sh on $(date)

# OpenAI Configuration
OPENAI_API_KEY="${OPENAI_API_KEY}"
DEFAULT_ADB_MODEL="${DEFAULT_ADB_MODEL:-o4-mini}"
DEFAULT_MAX_TOKENS=${DEFAULT_MAX_TOKENS:-20000}

# Database Configuration
DATABASE_URL="${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/bazaar}"
DATABASE_URL_NON_POOLED="${DATABASE_URL_NON_POOLED:-$DATABASE_URL}"

# Authentication Configuration
AUTH_GITHUB_ID="${AUTH_GITHUB_ID}"
AUTH_GITHUB_SECRET="${AUTH_GITHUB_SECRET}"
AUTH_GOOGLE_ID="${AUTH_GOOGLE_ID}"
AUTH_GOOGLE_SECRET="${AUTH_GOOGLE_SECRET}"

# R2 Storage Configuration
R2_ENDPOINT="${R2_ENDPOINT}"
R2_ACCESS_KEY_ID="${R2_ACCESS_KEY_ID}"
R2_SECRET_ACCESS_KEY="${R2_SECRET_ACCESS_KEY}"
R2_BUCKET_NAME="${R2_BUCKET_NAME:-bazaar-vid-components}"
R2_PUBLIC_URL="${R2_PUBLIC_URL}"

# Other Required Settings
CRON_SECRET="${CRON_SECRET}"

# Feature Flags
USE_MESSAGE_BUS=true
DISABLE_BACKGROUND_WORKERS=false

# Log Configuration
LOG_DIR="/tmp/bazaar-logs"
A2A_LOG_DIR="/tmp/a2a-logs"
ERROR_LOG_DIR="/tmp/error-logs"
COMBINED_LOG_DIR="/tmp/combined-logs"
LOG_AGENT_URL="${LOG_AGENT_URL:-http://localhost:3002}"

# Task Processor Configuration
TASK_PROCESSOR_POLLING_INTERVAL=${TASK_PROCESSOR_POLLING_INTERVAL:-10000}
TASK_PROCESSOR_HEARTBEAT_INTERVAL=${TASK_PROCESSOR_HEARTBEAT_INTERVAL:-5000}
TASK_PROCESSOR_STARTUP_DELAY=${TASK_PROCESSOR_STARTUP_DELAY:-10000}
WORKER_POLLING_INTERVAL=${WORKER_POLLING_INTERVAL:-10000}

# Development Settings
WATCHPACK_POLLING=true
CHOKIDAR_USEPOLLING=true
NEXT_MANUAL_SIG_HANDLE=true
EOL

echo "✅ Environment file $ENV_FILE created successfully with real Codex environment variables!"
npm install